#!/bin/bash	

#
# DECLARE VARIABLE
#

source /opt/showipatlogon/SETTINGS

DELAY_IP=10   # How many secs to wait until we timeout to find an IP address.

if [ $1 == "nowait" ] ; then
  NOWAIT="yes"
else
  NOWAIT="no"
fi

#
# MAIN
#

adapter=""
adapter=$(route -n | grep "^0.0.0.0" | rev | cut -d' ' -f1 | rev)

if [ $NOWAIT == "no" ] ; then
  COUNTER=0
  FIRST_TIME=yes
  until ! [ -z "$adapter" ] || [ ${COUNTER} = ${DELAY_IP} ] ; do
     adapter=$(route -n | grep "^0.0.0.0" | rev | cut -d' ' -f1 | rev)
     COUNTER=$(( $COUNTER + 1 ))
     if [ $FIRST_TIME == "yes" ] && [ $COUNTER == 3 ] ; then
         printf "Looking for an IP address." > /dev/tty0
         FIRST_TIME=no
       else
         if (( $COUNTER > 3 )) ; then
           printf "." > /dev/tty0
         fi
     fi
     sleep 1
  done
fi

if [ -z "$adapter" ] ;
  then adapter=lo
fi

printf "$NC"

if [ "$adapter" = "lo" ] ; then 
     printf "${RED}${adapter}: ${CYAN}$(ifdata -pa $adapter) \n"
  else
    for iface in $(ifconfig | cut -d ' ' -f1| tr ':' '\n' | awk NF)
    do
          IP=$(ifdata -pa $iface)
          NOW=$(date +"%y-%m-%d %r")
	    
	  if [ "$IP" != "NON-IP" ] && [ "$iface" != "lo" ]  ; then
             if [ $NOWAIT == "no" ] ; then
	       printf "$NOW $iface $IP \n" >> ${INSTALL_FOLDER}/showipatlogon.log
             fi
             printf "${GREEN}${iface}: ${CYAN}$(ifdata -pa ${iface}) \n"
	  fi
    done 
fi

printf "$NC\n"

