#!/bin/bash

########################################################
#                                                      #
#  Symbolic links folder location                      #
#  ------------------------------                      #
#                                                      #
#  Folder location where the showipatlogon and showip  #
#  symbolic links will be located.                     #
#                                                      #
#  This location was chosen according to the FHS_3.0,  # 
#  and is included in the Arch linux $PATH variable.   #
#                                                      #
########################################################

SYMBOLIC_LINK_FOLDER=/usr/local/bin


#########################################################
#                                                       #
#  Install folder                                       #
#  --------------                                       #
#                                                       #
#  Folder location where all the files will be located  #
#  for execution.                                       #
#                                                       #
#  This location was chosen according to the FHS_3.0.   #
#                                                       #
#########################################################

INSTALL_FOLDER=/opt/showipatlogon


########################################################
#                                                      #
#  Terminal colors                                     #
#  ---------------                                     #
#                                                      #
#  Those variables will be used to make coloring text  # 
#  more friendly inside the bash code.                 #
#                                                      #
########################################################

BLACK='\033[1;30m'
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
MAGENTA='\033[1;35m'
CYAN='\033[1;36m'
WHITE='\033[1;37m'

BCK_BLACK='\033[1;40m'
BCK_RED='\033[1;41m'
BCK_GREEN='\033[1;42m'
BCK_YELLOW='\033[1;43m'
BCK_BLUE='\033[1;44m'
BCK_MAGENTA='\033[1;45m'
BCK_CYAN='\033[1;46m'
BCK_WHITE='\033[1;47m'

NC='\033[0m'
